language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=pyrest_client setup.py test
cache: pip
after_success:
  coveralls